#!/usr/bin/env bash
set -ex

# This is the master script for the capsule. When you click "Reproducible Run", the code in this file will execute.
bash test_tableII.sh "$@"

###### Uncomment to run test for table I
# bash test_tableI.sh "$@"
