# hash:sha256:70872e630786398ae079faa35acd362dd677786359128b5e03fe2317245e8e9c
FROM registry.codeocean.com/codeocean/miniconda3:4.9.2-python3.8-ubuntu20.04

ARG DEBIAN_FRONTEND=noninteractive

RUN pip install -U --no-cache-dir \
    multiprocess==0.70.12.2 \
    mystic==0.3.8 \
    subprocess32==3.5.4
